### ISSUE TITLE
Raspberry Pi 3 and ACD-300

### ISSUE THREAD

**Issue by Dendrowen** [jeroenst/433mhzforrpi#2]
Hello. I cannot get the ACD-300 to learn. It just... does nothing.
- I ran your install file
- wiring Pi is ok
- This is my result:

`pi@raspberrypi:~/Programs/Domotica/wiringPi/wiringPi/433mhzforrpi $ sudo ./kaku 123 1 on`
`Sending message to 433mhzdaemon.... Done`
 `Message Queue Closed
`

I do not have other KaKu modules to test it on. Please help!

**Comment by jeroenst** [comment]
This should be ok...
